external:
         api:
          key: test_da11ed727a9845c0849ecd1d963d28a68a7db36a3e7cf331b34421f8fee86293d6d9bb768669d55731cfd7b4d1dd23d2
          url: https://open.api.nexon.com
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost/mapleCombat"
    username: "root"
    password: "62845"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties :
      hibernate:
        show_sql: true
        format_sql:
        dialect : org.hibernate.dialect.MySQL8Dialect
